#!/usr/bin/env python3
"""Writes docs/phase1/PHASE1_SOURCE.md: the complete source of every Phase 1 file, in one
document, each file under its exact Studio path and instance class.

Run from anywhere: python3 PumpkinFarm/tools/bundle_phase1.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "phase1", "PHASE1_SOURCE.md")

# (section title, [paths relative to PumpkinFarm/])
SECTIONS = [
    ("Project", ["default.project.json"]),
    ("Shared: constants", [f"src/shared/Constants/{n}.luau" for n in
        ["MatchState", "LifeState", "ResultCode", "Attributes", "CollisionGroup", "CurrencyId"]]),
    ("Shared: types and data", ["src/shared/Types/Types.luau", "src/shared/Data/Rarity.luau", "src/shared/Data/Palette.luau"]),
    ("Shared: utilities", [f"src/shared/Utilities/{n}.luau" for n in
        ["TableUtil", "Validate", "Result", "Clock", "MathUtil", "Format", "WeightedRandom"]]),
    ("Shared: classes (Janitor, Signal, StateMachine, TokenBucket)", [f"src/shared/Classes/{n}.luau" for n in
        ["Janitor", "Signal", "StateMachine", "TokenBucket"]]),
    ("Shared: configuration", [f"src/shared/Config/{n}.luau" for n in
        ["NetworkConfig", "CropConfig", "SeedConfig", "EnemyConfig", "WaveConfig", "ClassConfig", "WeaponConfig",
         "DefenseConfig", "EconomyConfig", "StatusEffectConfig", "MatchConfig", "DifficultyConfig", "AudioConfig"]]),
    ("Server: bootstrap", ["src/server/Bootstrap.server.luau", "src/server/Registry.luau"]),
    ("Server: networking", ["src/server/Services/RemoteService.luau", "src/server/Systems/RemoteRateLimiter.luau"]),
    ("Server: data", [f"src/server/Data/{n}.luau" for n in
        ["DataConfig", "ProfileTemplate", "Migrations", "SessionLockedStore", "ProfileServiceWrapper"]]
        + ["src/server/Services/DataService.luau"]),
    ("Server: currencies", [f"src/server/Services/{n}.luau" for n in ["CandyService", "MatchCoinService", "CurrencyService"]]),
    ("Server: players", ["src/server/Classes/PlayerSession.luau", "src/server/Services/PlayerService.luau"]),
    ("Server: match state machine", ["src/server/Classes/Match.luau", "src/server/Services/MatchService.luau"]),
    ("Client: bootstrap and modules", ["src/client/ClientBootstrap.client.luau"]
        + [f"src/client/Modules/{n}.luau" for n in ["ControllerRegistry", "Net", "ClientState"]]),
]


def studio_path(rel):
    if rel == "default.project.json":
        return "Rojo project file (not an Instance)", "-"
    mapping = [("src/shared/", "ReplicatedStorage.Shared."), ("src/server/", "ServerScriptService.Server."),
               ("src/client/", "StarterPlayer.StarterPlayerScripts.Client.")]
    for prefix, target in mapping:
        if rel.startswith(prefix):
            name = rel[len(prefix):]
            cls = "ModuleScript"
            if name.endswith(".server.luau"):
                cls, name = "Script", name[: -len(".server.luau")]
            elif name.endswith(".client.luau"):
                cls, name = "LocalScript", name[: -len(".client.luau")]
            else:
                name = name[: -len(".luau")]
            return target + name.replace("/", "."), cls
    raise ValueError(rel)


def main():
    parts, index, total_lines, count = [], [], 0, 0
    for title, files in SECTIONS:
        anchor = title.lower().replace(":", "").replace("(", "").replace(")", "").replace(",", "").replace(" ", "-")
        index.append(f"- [{title}](#{anchor})")
        parts.append(f"\n## {title}\n")
        for rel in files:
            with open(os.path.join(ROOT, rel), encoding="utf-8") as handle:
                source = handle.read().rstrip("\n")
            path, cls = studio_path(rel)
            lang = "json" if rel.endswith(".json") else "lua"
            lines = source.count("\n") + 1
            total_lines += lines
            count += 1
            parts.append(f"\n### `{path}`\n\n{cls} · `PumpkinFarm/{rel}` · {lines} lines\n\n```{lang}\n{source}\n```\n")
    header = (
        "# Phase 1: complete source\n\n"
        "Generated by `tools/bundle_phase1.py` from the repository; do not edit by hand. "
        f"{count} files, {total_lines} lines. The architecture, Studio checklist and verification "
        "checklist are in [PHASE1.md](PHASE1.md).\n\n"
        "Each heading is the exact Studio path. Create a ModuleScript (or the Script / LocalScript "
        "shown) with that name and paste the block, or skip all of this and open the built place file.\n\n"
        + "\n".join(index) + "\n"
    )
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(header + "".join(parts))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {count} files, {total_lines} lines")


if __name__ == "__main__":
    main()
